# Generated by Django 2.2.7 on 2020-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofilecontent',
            name='usertype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navigationcontent',
            name='usertype',
            field=models.TextField(null=True),
        ),
    ]
