# Generated by Django 2.2.7 on 2020-01-06 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omosapp', '0005_clienttag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrate',
            name='user',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='clientUsername',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='clientUsername',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderID',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderID',
        ),
        migrations.AddField(
            model_name='chart',
            name='clientItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omosapp.ClientItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='clientItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omosapp.ClientItem'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='clientName',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='clientrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='customerCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omosapp.ClientCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('customer', 'clientItem', 'clientName')},
        ),
        migrations.AlterUniqueTogether(
            name='clientitem',
            unique_together={('user', 'name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'clientItem')},
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ClientRate',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='clientItemName',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='item',
        ),
    ]
