# Generated by Django 2.2.7 on 2020-01-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0006_auto_20200106_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='clientTags',
            field=models.TextField(null=True),
        ),
    ]
