# Generated by Django 2.2.7 on 2020-01-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0008_auto_20200111_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcategory',
            name='item1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='item8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='price8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
