# Generated by Django 2.2.7 on 2020-01-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0009_auto_20200111_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientItemTuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
