# Generated by Django 2.2.7 on 2020-01-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0010_clientitemtuple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientItemTuple',
        ),
    ]
