# Generated by Django 2.2.7 on 2020-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0011_delete_clientitemtuple'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='itemCount',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
