# Generated by Django 2.2.7 on 2020-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0014_auto_20200112_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientAvgTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientDistrict',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientFax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientManagerEmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientMinPrice',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientName',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientNeighborhood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientTags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='clientrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='customerCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
