# Generated by Django 2.2.7 on 2020-01-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0015_auto_20200112_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='clientNameText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
