# Generated by Django 2.2.7 on 2020-01-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0016_chart_clientnametext'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clientUsername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
