# Generated by Django 2.2.7 on 2020-01-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omosapp', '0017_order_clientusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
